language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - pytest py/lyacolore/test/test_cor.py -s
